name: CI (terraform validate)
on:
  pull_request:
jobs:
  tf:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('**/*.tf') != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.6'
      - name: terraform fmt/validate (repo root)
        run: |
          terraform fmt -check || true
          terraform init -input=false -backend=false || true
          terraform validate || true
