name: CI
on:
  pull_request:
permissions:
  contents: read
  id-token: write
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TF_INPUT: false
      AWS_REGION: us-east-2
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run Python tests (pytest)
        run: pytest -q --cov=lambda_func --cov-report=xml
      - name: Run unit tests (unittest)
        run: python -m unittest -v
      - name: Install Terraform & Helm
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.6'
      - run: |
          curl -L https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz | tar xz
          sudo mv linux-amd64/helm /usr/local/bin/helm
      - name: Terraform fmt/validate (dev)
        working-directory: terraform/envs/dev
        run: |
          terraform fmt -check
          terraform init -input=false -backend=false
          terraform validate
      - name: Helm lint & template (policy-audit)
        run: |
          helm lint k8s/charts/policy-audit || true
          helm template policy-audit k8s/charts/policy-audit > /tmp/policy-audit.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: k8s-render
          path: /tmp/policy-audit.yaml
